#!/usr/bin/env python3
"""Build the Stillness Desk altar layers from Codex raw sheets.

Raw sheets (tools/art_sources/checkpoint/raw/stillness_{desk,roots,props,misc}_raw.png)
are generated by Codex on flat magenta; see
tools/art_sources/checkpoint/prompts/stillness_desk_layers.md.

Pipeline: magenta key -> connected components -> cluster components into items
(nearby components merge) -> order items per sheet -> rescale each layer to the
in-game texel density (1 output px = 0.175 world units, same as Luz's 512 px
cells) -> trim -> export assets/world/stillness_desk/<layer>.png and layout.json.

Coordinates in layout.json are in output ("source") px. The desk origin is the
floor line under the desk centre; x grows right, y grows UP. Each layer lists a
`pivot` (px inside the exported image, top-left origin) and `offset` (where that
pivot sits relative to the desk origin). Godot position of the image top-left is
origin + ((offset.x - pivot.x), -(offset.y) - pivot.y) * WORLD_SCALE.

The lit floor ring is derived from the unlit one so both have identical geometry.
"""

from __future__ import annotations

import json
from pathlib import Path
from statistics import median

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

import process_luz_combat_hits as pch

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "tools" / "art_sources" / "checkpoint" / "raw"
PREVIEW_DIR = ROOT / "tools" / "art_sources" / "checkpoint" / "preview"
OUT_DIR = ROOT / "assets" / "world" / "stillness_desk"
LUZ_SHEET = ROOT / "assets" / "player" / "luz" / "luz_rest_sheet.png"

WORLD_SCALE = 0.175
SEAT_HEIGHT = 150  # desk top above the floor line, matches luz_rest_sheet seat lift
LUZ_CELL = 512
LUZ_FEET_ROW = pch.FEET_ROW
LUZ_ANCHOR_X = 256  # idle centroid used by process_luz_rest_ritual.py
MIN_COMPONENT_PX = 120
RESAMPLE = Image.LANCZOS

# Sheet -> ordered item names. "rows" splits items into rows by centre y before
# sorting left to right; None means a single left-to-right row (or top-to-bottom
# when "vertical").
SHEETS = {
    "stillness_desk_raw.png": {"items": ["desk_body", "arch_frame"], "gap": 30},
    "stillness_roots_raw.png": {"items": ["roots", "floor_ring"], "gap": 60, "vertical": True},
    "stillness_props_raw.png": {
        "items": ["candle_jar", "flame_0", "flame_1", "flame_2", "flame_3", "inkwell", "ink_box", "backpack_prop"],
        "gap": 30,
        "rows": 2,
    },
    "stillness_misc_raw.png": {
        "items": ["paper_0", "paper_1", "paper_2", "paper_3", "pendulum", "pendulum_bracket"],
        "gap": 30,
    },
}

# Layer -> (axis, target px, optional x-stretch). Group scales share one factor.
SCALE_RULES = {
    "desk_body": ("h", SEAT_HEIGHT, 1.2),
    "arch_frame": ("h", 720, 1.2),
    "roots": ("w", 470, 1.0),
    "floor_ring": ("w", 700, 1.0),
    "candle_jar": ("h", 34, 1.0),
    "flame": ("h", 24, 1.0),
    "inkwell": ("h", 72, 1.0),
    "ink_box": ("w", 54, 1.0),
    "paper": ("h", 46, 1.0),
    "pendulum": ("h", 175, 1.0),
    "pendulum_bracket": ("w", 62, 1.0),
    "backpack_prop": ("h", 96, 1.0),
}

# Z order back to front (higher = in front).
Z = {
    "arch_frame": 0, "pendulum_bracket": 1, "pendulum": 2, "floor_ring_unlit": 3, "floor_ring_lit": 4,
    "desk_body": 5, "ink_box": 6, "candle_jar": 7, "flame": 8, "inkwell": 9, "roots_left": 10, "roots_right": 10,
    "papers": 11, "backpack_prop": 12,
}

# Suggested prop x on the desk top, relative to the desk centre (source px).
ARCH_DIM = 0.62
ROOTS_CLEAR_HALF = 65  # centre 40% of the 324 px desk stays clear of roots
ROOTS_FALLOFF = 8
ROOTS_LEG_X = 140  # inner edge of each root cluster sits at the desk leg
ROOTS_ORPHAN_PX = 60
JAR_X = -125
INKWELL_X = 105
INK_BOX_X = 138
BACKPACK_X = -125


FRINGE_ALPHA = 30
FRINGE_MAGENTA_LEAD = 60


def key_magenta(raw: Image.Image) -> Image.Image:
    im = raw.convert("RGBA")
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            m = min(r, b) - g
            if m > 100:
                px[x, y] = (0, 0, 0, 0)
            elif m > 30:
                px[x, y] = (max(0, r - m), g, max(0, b - m), min(a, int(255 * (100 - m) / 70)))
    return im


def despill_faint_magenta(im: Image.Image) -> Image.Image:
    """Drop near-transparent magenta fringe left by keying and resampling."""
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if 0 < a <= FRINGE_ALPHA and min(r, b) - g > FRINGE_MAGENTA_LEAD:
                px[x, y] = (0, 0, 0, 0)
    return im


def _gap(a: tuple[int, int, int, int], b: tuple[int, int, int, int]) -> float:
    dx = max(a[0] - b[2], b[0] - a[2], 0)
    dy = max(a[1] - b[3], b[1] - a[3], 0)
    return max(dx, dy)


def split_items(keyed: Image.Image, spec: dict, name: str) -> dict[str, Image.Image]:
    labels, sizes, boxes = pch.label_components(keyed.getchannel("A").tobytes(), keyed.width, keyed.height)
    comps = [lbl for lbl, size in sizes.items() if size >= MIN_COMPONENT_PX]
    parent = {lbl: lbl for lbl in comps}

    def find(v: int) -> int:
        while parent[v] != v:
            parent[v] = parent[parent[v]]
            v = parent[v]
        return v

    for i, a in enumerate(comps):
        for b in comps[i + 1:]:
            if _gap(boxes[a], boxes[b]) <= spec["gap"]:
                parent[find(a)] = find(b)
    clusters: dict[int, list[int]] = {}
    for lbl in comps:
        clusters.setdefault(find(lbl), []).append(lbl)
    items = []
    for members in clusters.values():
        box = (
            min(boxes[m][0] for m in members), min(boxes[m][1] for m in members),
            max(boxes[m][2] for m in members), max(boxes[m][3] for m in members),
        )
        items.append((box, set(members)))
    expected = spec["items"]
    if len(items) != len(expected):
        raise ValueError(f"{name}: found {len(items)} items, expected {len(expected)}: {[i[0] for i in items]}")
    if spec.get("vertical"):
        items.sort(key=lambda it: it[0][1])
    elif spec.get("rows"):
        mid = keyed.height / 2
        items.sort(key=lambda it: ((it[0][1] + it[0][3]) / 2 > mid, it[0][0]))
    else:
        items.sort(key=lambda it: it[0][0])
    out: dict[str, Image.Image] = {}
    for item_name, (box, members) in zip(expected, items):
        crop = keyed.crop((box[0], box[1], box[2] + 1, box[3] + 1)).copy()
        px = crop.load()
        for cy in range(crop.height):
            for cx in range(crop.width):
                if labels[(box[1] + cy) * keyed.width + box[0] + cx] not in members:
                    px[cx, cy] = (0, 0, 0, 0)
        out[item_name] = trim(crop)
    return out


def trim(im: Image.Image) -> Image.Image:
    box = im.getchannel("A").point(lambda v: 255 if v > 12 else 0).getbbox()
    return im.crop(box) if box else im


def resize(im: Image.Image, width: int, height: int) -> Image.Image:
    width, height = max(1, width), max(1, height)
    return pch.unpremultiply(pch.premultiply(im).resize((width, height), RESAMPLE))


def scaled(im: Image.Image, rule_key: str, factor: float | None = None) -> tuple[Image.Image, float]:
    axis, target, stretch = SCALE_RULES[rule_key]
    if factor is None:
        factor = target / im.height if axis == "h" else target / (im.width * stretch)
    return trim(resize(im, round(im.width * factor * stretch), round(im.height * factor))), factor


def inner_apex_row(arch: Image.Image) -> int:
    """First transparent row (from the top) down the centre column: the arch's inner apex."""
    alpha = arch.getchannel("A")
    cx = arch.width // 2
    seen_opaque = False
    for y in range(arch.height):
        opaque = alpha.getpixel((cx, y)) > 40
        if opaque:
            seen_opaque = True
        elif seen_opaque:
            return y
    return arch.height // 2


def split_roots(roots: Image.Image) -> tuple[Image.Image, Image.Image]:
    """Cut the centre out of the roots (soft falloff) and return (left, right) halves."""
    cx = roots.width / 2
    halves = []
    for side in (-1, 1):
        half = roots.copy()
        px = half.load()
        for y in range(half.height):
            for x in range(half.width):
                d = (x + 0.5 - cx) * side  # distance past the centre toward this side
                r, g, b, a = px[x, y]
                if a == 0:
                    continue
                k = min(1.0, max(0.0, (d - ROOTS_CLEAR_HALF) / ROOTS_FALLOFF))
                px[x, y] = (r, g, b, int(a * k))
        labels, sizes, _ = pch.label_components(half.getchannel("A").tobytes(), half.width, half.height)
        for i, lbl in enumerate(labels):
            if lbl and sizes[lbl] < ROOTS_ORPHAN_PX:
                px[i % half.width, i // half.width] = (0, 0, 0, 0)
        halves.append(trim(half))
    return halves[0], halves[1]


def dim(im: Image.Image, factor: float) -> Image.Image:
    """Darken RGB (keeps alpha) so the backdrop recedes behind Luz and the altar."""
    r, g, b, a = im.split()
    return Image.merge("RGBA", (r.point(lambda v: int(v * factor)), g.point(lambda v: int(v * factor)), b.point(lambda v: int(v * factor)), a))


def is_amber(r: int, g: int, b: int) -> bool:
    return r > 150 and r > g + 25 and r - b > 90


def build_rings(ring: Image.Image) -> tuple[Image.Image, Image.Image]:
    pad = 14
    base = Image.new("RGBA", (ring.width + pad * 2, ring.height + pad * 2), (0, 0, 0, 0))
    base.alpha_composite(ring, (pad, pad))
    unlit = base.copy()
    lit = base.copy()
    up, lp = unlit.load(), lit.load()
    glow_mask = Image.new("L", base.size, 0)
    gp = glow_mask.load()
    for y in range(base.height):
        for x in range(base.width):
            r, g, b, a = up[x, y]
            if a > 20 and is_amber(r, g, b):
                up[x, y] = (int(r * 0.52), int(g * 0.46), int(b * 0.42), a)
                lp[x, y] = (255, min(255, int(g * 1.2) + 40), min(255, b + 70), a)
                gp[x, y] = a
    glow = glow_mask.filter(ImageFilter.GaussianBlur(5)).point(lambda v: min(255, v * 2))
    halo = Image.new("RGBA", base.size, (255, 176, 64, 0))
    halo.putalpha(glow.point(lambda v: int(v * 0.55)))
    lit = Image.alpha_composite(halo, lit)
    return unlit, lit


def flame_strip(frames: list[Image.Image]) -> tuple[Image.Image, tuple[int, int]]:
    cw = max(f.width for f in frames) + 2
    ch = max(f.height for f in frames)
    strip = Image.new("RGBA", (cw * len(frames), ch), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        strip.alpha_composite(f, (i * cw + (cw - f.width) // 2, ch - f.height))
    return strip, (cw, ch)


def entry(name: str, im: Image.Image, pivot: tuple[int, int], offset: tuple[float, float], **extra) -> dict:
    data = {
        "file": f"{name}.png", "size": [im.width, im.height], "pivot": [pivot[0], pivot[1]],
        "offset": [round(offset[0], 1), round(offset[1], 1)], "z": Z[extra.pop("z_key", name)],
    }
    data.update(extra)
    return data


def build() -> tuple[dict[str, Image.Image], dict]:
    parts: dict[str, Image.Image] = {}
    for sheet, spec in SHEETS.items():
        parts.update(split_items(key_magenta(Image.open(RAW_DIR / sheet)), spec, sheet))

    layers: dict[str, Image.Image] = {}
    meta: dict[str, dict] = {}

    desk, _ = scaled(parts["desk_body"], "desk_body")
    layers["desk_body"] = desk
    meta["desk_body"] = entry("desk_body", desk, (desk.width // 2, desk.height), (0, 0))

    arch, _ = scaled(parts["arch_frame"], "arch_frame")
    arch = dim(arch, ARCH_DIM)
    layers["arch_frame"] = arch
    meta["arch_frame"] = entry("arch_frame", arch, (arch.width // 2, arch.height), (0, 0))
    apex_y = arch.height - inner_apex_row(arch)  # height of the inner apex above the floor line

    bracket, _ = scaled(parts["pendulum_bracket"], "pendulum_bracket")
    layers["pendulum_bracket"] = bracket
    meta["pendulum_bracket"] = entry("pendulum_bracket", bracket, (bracket.width // 2, 0), (0, apex_y + 2))
    ring_center_y = round(bracket.height * 0.9)
    pivot_world_y = apex_y + 2 - ring_center_y

    pend, _ = scaled(parts["pendulum"], "pendulum")
    layers["pendulum"] = pend
    pend_pivot = (pend.width // 2, round(pend.height * 0.045))
    meta["pendulum"] = entry("pendulum", pend, pend_pivot, (0, pivot_world_y))

    roots, _ = scaled(parts["roots"], "roots")
    left, right = split_roots(roots)
    layers["roots_left"], layers["roots_right"] = left, right
    meta["roots_left"] = entry("roots_left", left, (left.width - 1, left.height), (-ROOTS_LEG_X, -4))
    meta["roots_right"] = entry("roots_right", right, (0, right.height), (ROOTS_LEG_X, -4))

    ring, _ = scaled(parts["floor_ring"], "floor_ring")
    unlit, lit = build_rings(ring)
    layers["floor_ring_unlit"], layers["floor_ring_lit"] = unlit, lit
    ring_pivot = (unlit.width // 2, unlit.height // 2)
    for key in ("floor_ring_unlit", "floor_ring_lit"):
        meta[key] = entry(key, layers[key], ring_pivot, (0, 0), ring_inner_padding=14)

    jar, _ = scaled(parts["candle_jar"], "candle_jar")
    layers["candle_jar"] = jar
    meta["candle_jar"] = entry("candle_jar", jar, (jar.width // 2, jar.height), (JAR_X, SEAT_HEIGHT))

    flame_raw = [parts[f"flame_{i}"] for i in range(4)]
    flame_factor = SCALE_RULES["flame"][1] / median(f.height for f in flame_raw)
    flames = [scaled(f, "flame", flame_factor)[0] for f in flame_raw]
    strip, cell = flame_strip(flames)
    layers["flame"] = strip
    meta["flame"] = entry(
        "flame", strip, (cell[0] // 2, cell[1]), (JAR_X, SEAT_HEIGHT + round(jar.height * 0.6)),
        frames=4, frame_size=list(cell), fps_suggested=8,
    )

    ink, _ = scaled(parts["inkwell"], "inkwell")
    layers["inkwell"] = ink
    # pivot on the glass body, not on the quill tip: use the bottom centre of the bottom 45% band.
    band = ink.crop((0, int(ink.height * 0.55), ink.width, ink.height)).getchannel("A").getbbox()
    ink_pivot = (((band[0] + band[2]) // 2) if band else ink.width // 2, ink.height)
    meta["inkwell"] = entry("inkwell", ink, ink_pivot, (INKWELL_X, SEAT_HEIGHT))

    box, _ = scaled(parts["ink_box"], "ink_box")
    layers["ink_box"] = box
    meta["ink_box"] = entry("ink_box", box, (box.width // 2, box.height), (INK_BOX_X, SEAT_HEIGHT))

    paper_raw = [parts[f"paper_{i}"] for i in range(4)]
    paper_factor = SCALE_RULES["paper"][1] / median(p.height for p in paper_raw)
    paper_offsets = [(-125, 250), (135, 290), (-100, 370), (120, 215)]
    paper_meta = []
    for i, raw_paper in enumerate(paper_raw):
        p, _ = scaled(raw_paper, "paper", paper_factor)
        layers[f"paper_{i}"] = p
        paper_meta.append(entry(f"paper_{i}", p, (p.width // 2, p.height // 2), paper_offsets[i], z_key="papers"))
    meta["papers"] = {"note": "suggested orbit/lift start offsets; pivots are the image centres", "items": paper_meta}

    pack, _ = scaled(parts["backpack_prop"], "backpack_prop")
    layers["backpack_prop"] = pack
    meta["backpack_prop"] = entry("backpack_prop", pack, (pack.width // 2, pack.height), (BACKPACK_X, 0))

    layout = {
        "version": 1,
        "world_scale": WORLD_SCALE,
        "units": "source px; origin = floor line under desk centre; x right, y up; pivot in image px (top-left origin)",
        "desk_top_height": SEAT_HEIGHT,
        "seat_point": [0, SEAT_HEIGHT],
        "luz": {
            "note": "luz_rest_sheet cells are 512 px; place cell point (anchor_x, feet_row) at the desk origin. "
                    "Seated frames already carry the 150 px lift, so the seat lands on desk_top_height.",
            "cell_anchor": [LUZ_ANCHOR_X, LUZ_FEET_ROW],
            "stand_x": 0,
        },
        "backpack_spot": [BACKPACK_X, 0],
        "pendulum": {"pivot": [0, pivot_world_y], "length": pend.height - pend_pivot[1]},
        "arch_inner_apex_height": apex_y,
        "layers": meta,
    }
    return layers, layout


def _font():
    try:
        return ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 14)
    except OSError:
        return ImageFont.load_default()


def compose(layers: dict[str, Image.Image], layout: dict, scale: float, luz: bool = True, lit: bool = False) -> Image.Image:
    """Assemble all layers per layout.json over a dark blue background (scale in px per source px)."""
    width, height = 900, 900
    canvas = Image.new("RGBA", (width, height), (10, 16, 34, 255))
    meta = layout["layers"]
    items: list[tuple[int, str, Image.Image, list[float], list[int]]] = []
    for key, m in meta.items():
        if key == "papers":
            for p in m["items"]:
                items.append((p["z"], p["file"][:-4], layers[p["file"][:-4]], p["offset"], p["pivot"]))
            continue
        if key == "floor_ring_lit" and not lit:
            continue
        if key == "floor_ring_unlit" and lit:
            continue
        im = layers[key]
        if key == "flame":
            cw = m["frame_size"][0]
            im = im.crop((0, 0, cw, im.height))
        items.append((m["z"], key, im, m["offset"], m["pivot"]))
    luz_z = 8.5
    if luz:
        sheet = Image.open(LUZ_SHEET).convert("RGBA")
        frame = sheet.crop((0, 2 * LUZ_CELL, LUZ_CELL, 3 * LUZ_CELL))  # rest_sit frame 0 (cell 8)
        items.append((luz_z, "luz", frame, [0, 0], list(layout["luz"]["cell_anchor"])))
    items.sort(key=lambda it: it[0])
    for _, key, im, offset, pivot in items:
        if scale != 1:
            im = resize(im, round(im.width * scale), round(im.height * scale))
        cx = width // 2 + offset[0] * scale
        cy = (height - 90 * scale) - offset[1] * scale
        canvas.alpha_composite(im, (round(cx - pivot[0] * scale), round(cy - pivot[1] * scale)))
    return canvas


def compose_scaled(layers: dict[str, Image.Image], layout: dict, scale: float, lit: bool = False) -> Image.Image:
    return compose(layers, layout, scale, True, lit)


def contact_sheet(layers: dict[str, Image.Image]) -> Image.Image:
    cell = 260
    names = list(layers)
    cols = 5
    rows = (len(names) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols * cell, rows * cell), (10, 16, 34, 255))
    draw = ImageDraw.Draw(sheet)
    for i, name in enumerate(names):
        im = layers[name]
        fit = min(1.0, (cell - 30) / im.width, (cell - 40) / im.height)
        if fit < 1:
            im = resize(im, round(im.width * fit), round(im.height * fit))
        cx, cy = (i % cols) * cell, (i // cols) * cell
        bg = Image.new("RGBA", (cell - 4, cell - 4), (26, 34, 60, 255))
        sheet.alpha_composite(bg, (cx + 2, cy + 2))
        sheet.alpha_composite(im, (cx + (cell - im.width) // 2, cy + 22 + (cell - 22 - im.height) // 2))
        draw.text((cx + 6, cy + 4), f"{name} {layers[name].width}x{layers[name].height}", fill=(255, 220, 120, 255), font=_font())
    return sheet


def main() -> int:
    layers, layout = build()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    for name, im in layers.items():
        despill_faint_magenta(im).save(OUT_DIR / f"{name}.png")
    (OUT_DIR / "layout.json").write_text(json.dumps(layout, indent=2) + "\n")
    contact_sheet(layers).save(PREVIEW_DIR / "layers_contact.png")
    for scale, tag in ((1.0, "1x"), (0.175 * 4, "game4x")):
        compose_scaled(layers, layout, scale, lit=False).save(PREVIEW_DIR / f"composite_{tag}.png")
    compose_scaled(layers, layout, 1.0, lit=True).save(PREVIEW_DIR / "composite_1x_lit.png")
    print(f"Wrote {len(layers)} layers to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
