#!/usr/bin/env python3
"""Build Luz's Stillness Desk rest-ritual clips (mount, sit, dismount).

Raw sheets (tools/art_sources/luz/raw/rest_*_raw.png, 1536x1024, 4x2 cells of
384x512) are generated by Codex; see tools/art_sources/luz/prompts/rest_ritual.md.

Unlike process_luz_sheet.py (which drops every frame's lowest pixel on the feet
row), these clips need real vertical motion: Luz rises onto a desk that is NOT
part of the sprite. Each frame therefore carries an explicit `lift` -- how many
output pixels its lowest opaque row sits ABOVE the shared feet row (413). Grounded
frames have lift 0; seated frames have lift SEAT_HEIGHT; hop frames sit between.
Raw sheets differ in drawn scale, so each clip has its own measured scale that
matches the locomotion idle standing height (~331 px) / seated height.

Horizontal placement anchors the alpha centroid of every frame to the centroid of
the locomotion idle frame (plus an optional per-frame dx), so the body does not
slide across frames. Output: assets/player/luz/luz_rest_sheet.png and the
`luz_rest_sheet.png` section of animation_manifest.json. Existing sheets are not
touched.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

import process_luz_combat_hits as pch

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "tools" / "art_sources" / "luz" / "raw"
PREVIEW_DIR = ROOT / "tools" / "art_sources" / "luz" / "preview"
ASSET_DIR = ROOT / "assets" / "player" / "luz"
MANIFEST_PATH = ASSET_DIR / "animation_manifest.json"
SHEET_NAME = "luz_rest_sheet.png"

RAW_COLUMNS = 4
RAW_CELL_W = 384
RAW_CELL_H = 512
OUT_CELL = pch.OUT_CELL_SIZE
OUT_COLUMNS = 4
FEET_ROW = pch.FEET_ROW
MIN_COMPONENT_PX = 400

# Height of the (undrawn) desk-top sitting surface above the floor, in output px.
SEAT_HEIGHT = 150

CLIPS = {
    "rest_mount": {
        "raw_file": "rest_mount_raw.png",
        "scale": 0.81,
        "source_frames": [0, 1, 2, 3, 4, 5, 6, 7],
        "lifts": [0, 0, 0, 0, 20, 34, SEAT_HEIGHT, SEAT_HEIGHT],
        "dx": [0, 0, 0, 0, 0, 0, 0, 0],
    },
    "rest_sit": {
        "raw_file": "rest_sit_raw.png",
        "scale": 0.64,
        # Row-2 frames only: row-1 frames stretch the torso too far to loop.
        "source_frames": [7, 6, 4, 5],
        "lifts": [SEAT_HEIGHT] * 4,
        "dx": [0, 0, 0, 0],
    },
    "rest_dismount": {
        "raw_file": "rest_dismount_raw.png",
        "scale": 0.85,
        "source_frames": [0, 1, 2, 3, 4, 5, 6, 7],
        "lifts": [SEAT_HEIGHT, 48, 60, 0, 0, 0, 0, 0],
        "dx": [0, -35, -20, 0, 0, 0, 0, 0],
    },
}


def _font():
    try:
        return ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 20)
    except OSError:
        return ImageFont.load_default()


def key_magenta(raw: Image.Image) -> Image.Image:
    """Turn a magenta-background raw sheet into real alpha (no-op for keyed alpha)."""
    im = raw.convert("RGBA")
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            m = min(r, b) - g
            if m > 100:
                px[x, y] = (0, 0, 0, 0)
            elif m > 30:
                px[x, y] = (max(0, r - m), g, max(0, b - m), min(a, int(255 * (100 - m) / 70)))
    return im


def raw_frames(raw: Image.Image, name: str) -> list[Image.Image]:
    if raw.size != (RAW_COLUMNS * RAW_CELL_W, 2 * RAW_CELL_H):
        raise ValueError(f"{name}: expected 1536x1024 raw sheet, got {raw.size}")
    labels, sizes, boxes = pch.label_components(raw.getchannel("A").tobytes(), raw.width, raw.height)
    votes: dict[int, Counter] = {}
    for index, label in enumerate(labels):
        if label and sizes[label] >= MIN_COMPONENT_PX:
            y, x = divmod(index, raw.width)
            cell = (y // RAW_CELL_H) * RAW_COLUMNS + min(x // RAW_CELL_W, RAW_COLUMNS - 1)
            votes.setdefault(label, Counter())[cell] += 1
    owned: dict[int, set[int]] = {cell: set() for cell in range(8)}
    for label, counter in votes.items():
        owned[counter.most_common(1)[0][0]].add(label)
    frames = []
    for cell in range(8):
        if not owned[cell]:
            raise ValueError(f"{name}: cell {cell} has no art")
        x0 = min(boxes[label][0] for label in owned[cell])
        y0 = min(boxes[label][1] for label in owned[cell])
        x1 = max(boxes[label][2] for label in owned[cell])
        y1 = max(boxes[label][3] for label in owned[cell])
        crop = raw.crop((x0, y0, x1 + 1, y1 + 1)).copy()
        pixels = crop.load()
        for cy in range(crop.height):
            for cx in range(crop.width):
                if labels[(y0 + cy) * raw.width + x0 + cx] not in owned[cell]:
                    pixels[cx, cy] = (0, 0, 0, 0)
        frames.append(crop)
    return frames


def centroid_x(im: Image.Image) -> float:
    alpha = im.getchannel("A").point(lambda v: 255 if v > 8 else 0)
    total = 0
    weighted = 0
    for x, count in enumerate(alpha.resize((im.width, 1), Image.BOX).tobytes()):
        total += count
        weighted += x * count
    return weighted / max(total, 1)


def idle_anchor_x() -> float:
    sheet = Image.open(ASSET_DIR / "luz_locomotion_sheet.png").convert("RGBA")
    return centroid_x(sheet.crop((0, 0, OUT_CELL, OUT_CELL)))


def place(source: Image.Image, scale: float, lift: int, dx: int, anchor_x: float, label: str) -> Image.Image:
    w, h = max(1, round(source.width * scale)), max(1, round(source.height * scale))
    scaled = pch.unpremultiply(pch.premultiply(source).resize((w, h), pch.RESAMPLE))
    left = round(anchor_x + dx - centroid_x(scaled))
    top = FEET_ROW - lift - (h - 1)
    if left < 0 or top < 0 or left + w > OUT_CELL or top + h > OUT_CELL:
        raise ValueError(f"{label}: art does not fit output cell (left={left}, top={top}, size={w}x{h})")
    out = Image.new("RGBA", (OUT_CELL, OUT_CELL), (0, 0, 0, 0))
    out.alpha_composite(scaled, (left, top))
    return out


def render_previews(sheet: Image.Image, clip: str, start: int, count: int) -> None:
    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    frames = []
    for i in range(count):
        cell = start + i
        col, row = cell % OUT_COLUMNS, cell // OUT_COLUMNS
        frames.append(sheet.crop((col * OUT_CELL, row * OUT_CELL, (col + 1) * OUT_CELL, (row + 1) * OUT_CELL)))
    rows = (count + 3) // 4
    timeline = Image.new("RGBA", (OUT_CELL * 4, OUT_CELL * rows), (30, 30, 34, 255))
    onion = Image.new("RGBA", (OUT_CELL, OUT_CELL), (30, 30, 34, 255))
    for i, frame in enumerate(frames):
        timeline.alpha_composite(frame, ((i % 4) * OUT_CELL, (i // 4) * OUT_CELL))
        ghost = frame.copy()
        if i < count - 1:
            ghost.putalpha(ghost.getchannel("A").point(lambda v: v * 35 // 100))
        onion.alpha_composite(ghost)
    for canvas, offsets in ((timeline, [(i % 4 * OUT_CELL, i // 4 * OUT_CELL) for i in range(count)]), (onion, [(0, 0)])):
        draw = ImageDraw.Draw(canvas)
        for ox, oy in offsets:
            draw.line((ox, oy + FEET_ROW, ox + OUT_CELL, oy + FEET_ROW), fill=(255, 0, 255, 200))
            draw.line((ox, oy + FEET_ROW - SEAT_HEIGHT, ox + OUT_CELL, oy + FEET_ROW - SEAT_HEIGHT), fill=(0, 255, 255, 200))
            draw.line((ox + 256, oy, ox + 256, oy + OUT_CELL), fill=(255, 255, 0, 90))
    draw = ImageDraw.Draw(timeline)
    for i in range(count):
        draw.text(((i % 4) * OUT_CELL + 6, (i // 4) * OUT_CELL + 6), str(i), fill=(255, 255, 0, 255), font=_font())
    timeline.save(PREVIEW_DIR / f"rest_timeline__{clip}.png")
    onion.save(PREVIEW_DIR / f"rest_onion__{clip}.png")


def main() -> int:
    anchor_x = idle_anchor_x()
    total = sum(len(c["source_frames"]) for c in CLIPS.values())
    rows = (total + OUT_COLUMNS - 1) // OUT_COLUMNS
    sheet = Image.new("RGBA", (OUT_COLUMNS * OUT_CELL, rows * OUT_CELL), (0, 0, 0, 0))
    layout: dict[str, list[int]] = {}
    cursor = 0
    for name, config in CLIPS.items():
        raw = key_magenta(Image.open(RAW_DIR / config["raw_file"]))
        sources = raw_frames(raw, name)
        start = cursor
        for local, src in enumerate(config["source_frames"]):
            frame = place(sources[src], config["scale"], config["lifts"][local], config["dx"][local], anchor_x, f"{name}[{local}]")
            sheet.alpha_composite(frame, ((cursor % OUT_COLUMNS) * OUT_CELL, (cursor // OUT_COLUMNS) * OUT_CELL))
            cursor += 1
        layout[name] = list(range(start, cursor))
    sheet.save(ASSET_DIR / SHEET_NAME)
    for name, indices in layout.items():
        render_previews(sheet, name, indices[0], len(indices))

    manifest = json.loads(MANIFEST_PATH.read_text())
    manifest["sheets"][SHEET_NAME] = {
        "grid": {"columns": OUT_COLUMNS, "rows": rows, "cell_width": OUT_CELL, "cell_height": OUT_CELL},
        "clips": layout,
        "rest_ritual": {
            "note": "Seated/hop frames sit above the feet row (413) by lift_px; the desk is not drawn.",
            "seat_height_px": SEAT_HEIGHT,
            "lift_px": {name: config["lifts"] for name, config in CLIPS.items()},
            "dx_px": {name: config["dx"] for name, config in CLIPS.items()},
        },
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Wrote {SHEET_NAME} ({sheet.width}x{sheet.height}); clips: {layout}; anchor_x={anchor_x:.1f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
